export const ERROR_SHOW = 'ERROR_SHOW';
export const ERROR_HIDE = 'ERROR_HIDE';

export const STATION_ADDED = 'STATION_ADDED';
export const STATION_UPDATED = 'STATION_UPDATED';
export const STATION_REMOVED = 'STATION_REMOVED';
export const STATION_SELECTED = 'STATION_SELECTED';
export const STATIONS_LOAD_BEGIN = 'STATIONS_LOAD_BEGIN';
export const STATIONS_LOAD_FAIL = 'STATIONS_LOAD_FAIL';
export const STATIONS_LOAD_SUCCESS = 'STATIONS_LOAD_SUCCESS';

export const EVENT_ADDED = 'EVENT_ADDED';
export const EVENT_UPDATED = 'EVENT_UPDATED';
export const EVENT_REMOVED = 'EVENT_REMOVED';
export const EVENT_SELECTED = 'EVENT_SELECTED';
export const EVENTS_LOAD_BEGIN = 'EVENTS_LOAD_BEGIN';
export const EVENTS_LOAD_FAIL = 'EVENTS_LOAD_FAIL';
export const EVENTS_LOAD_SUCCESS = 'EVENTS_LOAD_SUCCESS';

export const ROUTE_ADDED = 'ROUTE_ADDED';
export const ROUTE_UPDATED = 'ROUTE_UPDATED';
export const ROUTE_REMOVED = 'ROUTE_REMOVED';
export const ROUTE_SELECTED = 'ROUTE_SELECTED';
export const ROUTES_LOAD_BEGIN = 'ROUTES_LOAD_BEGIN';
export const ROUTES_LOAD_FAIL = 'ROUTES_LOAD_FAIL';
export const ROUTES_LOAD_SUCCESS = 'ROUTES_LOAD_SUCCESS';

export const SESSION_STARTED = 'SESSION_STARTED';
export const SESSION_ENDED = 'SESSION_ENDED';
export const SESSION_UPDATED = 'SESSION_UPDATED';