export const ERROR_SHOW = 'ERROR_SHOW';
export const ERROR_HIDE = 'ERROR_HIDE';

export const STATION_ADDED = 'STATION_ADDED';
export const STATION_UPDATED = 'STATION_UPDATED';
export const STATION_REMOVED = 'STATION_REMOVED';
export const STATIONS_LOAD_BEGIN = 'STATIONS_LOAD_BEGIN';
export const STATIONS_LOAD_FAIL = 'STATIONS_LOAD_FAIL';
export const STATIONS_LOAD_SUCCESS = 'STATIONS_LOAD_SUCCESS';

export const SESSION_STARTED = 'SESSION_STARTED';
export const SESSION_ENDED = 'SESSION_ENDED';
export const SESSION_UPDATED = 'SESSION_UPDATED';